# Generated by Django 2.1.7 on 2019-02-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyno', models.CharField(max_length=9)),
                ('agencyname', models.CharField(max_length=36)),
                ('agencytype', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testno', models.CharField(max_length=14)),
                ('testappl', models.CharField(max_length=12)),
                ('testappl_date', models.DateField()),
                ('testcont', models.CharField(max_length=12)),
                ('testcontno', models.CharField(max_length=11)),
                ('testcontmail', models.CharField(max_length=50)),
                ('testtype', models.CharField(max_length=10)),
                ('teststart_date', models.DateField()),
                ('testend_date', models.DateField()),
                ('teststatus', models.CharField(max_length=2)),
                ('agencyno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyApp.AgencyInfo')),
            ],
        ),
    ]
