# Generated by Django 2.1.5 on 2019-02-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyApp', '0003_auto_20190219_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyinfo',
            name='agencyname',
            field=models.CharField(max_length=36, verbose_name='销售商'),
        ),
        migrations.AlterField(
            model_name='agencyinfo',
            name='agencyno',
            field=models.CharField(max_length=9, verbose_name='销售商代码'),
        ),
        migrations.AlterField(
            model_name='agencyinfo',
            name='agencyonprd',
            field=models.CharField(max_length=2, verbose_name='已代销'),
        ),
        migrations.AlterField(
            model_name='agencyinfo',
            name='agencytype',
            field=models.CharField(max_length=4, verbose_name='销售商类型'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='testappl',
            field=models.CharField(max_length=12, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='testappldate',
            field=models.DateField(verbose_name='申请日'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='testcont',
            field=models.CharField(max_length=12, verbose_name='测试对接人'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='testcontmail',
            field=models.CharField(max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='testcontno',
            field=models.CharField(max_length=15, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='testenddate',
            field=models.DateField(verbose_name='测试结束日'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='testno',
            field=models.CharField(max_length=14, verbose_name='测试编号'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='teststartdate',
            field=models.DateField(verbose_name='测试开始日'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='teststatus',
            field=models.CharField(max_length=2, verbose_name='测试状态'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='testtype',
            field=models.CharField(max_length=10, verbose_name='测试类型'),
        ),
    ]
