# Generated by Django 2.1.5 on 2019-02-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyApp', '0005_auto_20190221_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyinfo',
            options={'verbose_name': '销售商信息', 'verbose_name_plural': '销售商信息'},
        ),
        migrations.AlterField(
            model_name='agencyinfo',
            name='agencyonprd',
            field=models.CharField(choices=[('已代销', '已代销'), ('未代销', '未代销')], max_length=4, verbose_name='是否代销'),
        ),
        migrations.AlterField(
            model_name='agencyinfo',
            name='color_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='teststatus',
            field=models.CharField(choices=[('0', '未开始'), ('1', '测试完成'), ('2', '测试中')], max_length=2, verbose_name='测试状态'),
        ),
    ]
