# Generated by Django 2.1.5 on 2019-02-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyApp', '0006_auto_20190221_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testinfo',
            options={'verbose_name': '测试信息', 'verbose_name_plural': '测试信息'},
        ),
        migrations.AlterField(
            model_name='agencyinfo',
            name='agencytype',
            field=models.CharField(choices=[('券商', '券商'), ('银行', '银行'), ('保险', '保险'), ('第三方', '第三方')], max_length=4, verbose_name='销售商类型'),
        ),
    ]
