# Generated by Django 2.1.5 on 2019-02-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencyApp', '0007_auto_20190221_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinfo',
            name='testno',
        ),
    ]
