# Generated by Django 2.1.5 on 2019-02-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyApp', '0008_remove_testinfo_testno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinfo',
            name='testenddate',
            field=models.DateField(blank=True, verbose_name='测试结束日'),
        ),
        migrations.AlterField(
            model_name='testinfo',
            name='testtype',
            field=models.CharField(blank=True, max_length=10, verbose_name='测试类型'),
        ),
    ]
