# Generated by Django 2.1.5 on 2019-02-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyApp', '0009_auto_20190227_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinfo',
            name='testenddate',
            field=models.DateField(blank=True, null=True, verbose_name='测试结束日'),
        ),
    ]
