# Generated by Django 2.1.5 on 2019-02-28 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencyApp', '0010_auto_20190227_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyinfo',
            name='color_code',
        ),
    ]
