# Generated by Django 2.1.5 on 2019-03-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyApp', '0011_remove_agencyinfo_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyinfo',
            name='agencytype',
            field=models.CharField(choices=[('券商', '券商'), ('银行', '银行'), ('保险', '保险2'), ('第三方', '第三方')], max_length=4, verbose_name='销售商类型'),
        ),
    ]
