# Generated by Django 2.1.5 on 2019-03-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyApp', '0012_auto_20190301_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyinfo',
            name='agencytype',
            field=models.CharField(choices=[('券商', '券商'), ('银行', '银行'), ('保险', '保险'), ('第三方', '第三方')], max_length=4, verbose_name='销售商类型'),
        ),
    ]
